/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOTATO_INGEST_TTL_PB_H_INCLUDED
#define PB_LOTATO_INGEST_TTL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(4) LotatoIngestTtl_pub_key_prefix_t;
/* LoDB `ingest_ttl` row (ramdisk): last successful ingest POST time keyed by node id prefix. */
typedef struct _LotatoIngestTtl {
    LotatoIngestTtl_pub_key_prefix_t pub_key_prefix;
    uint32_t last_posted_unix;
    uint32_t reserved;
} LotatoIngestTtl;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LotatoIngestTtl_init_default             {{0, {0}}, 0, 0}
#define LotatoIngestTtl_init_zero                {{0, {0}}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LotatoIngestTtl_pub_key_prefix_tag       1
#define LotatoIngestTtl_last_posted_unix_tag     2
#define LotatoIngestTtl_reserved_tag             3

/* Struct field encoding specification for nanopb */
#define LotatoIngestTtl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pub_key_prefix,    1) \
X(a, STATIC,   SINGULAR, UINT32,   last_posted_unix,   2) \
X(a, STATIC,   SINGULAR, UINT32,   reserved,          3)
#define LotatoIngestTtl_CALLBACK NULL
#define LotatoIngestTtl_DEFAULT NULL

extern const pb_msgdesc_t LotatoIngestTtl_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LotatoIngestTtl_fields &LotatoIngestTtl_msg

/* Maximum encoded size of messages (where known) */
#define LOTATO_INGEST_TTL_PB_H_MAX_SIZE          LotatoIngestTtl_size
#define LotatoIngestTtl_size                     18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
