/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOTATO_MESH_NODE_PB_H_INCLUDED
#define PB_LOTATO_MESH_NODE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) LotatoMeshNode_pub_key_t;
typedef PB_BYTES_ARRAY_T(32) LotatoMeshNode_name_t;
/* LoDB `mesh_nodes` row: persisted mesh advert snapshot for Lotato ingest. */
typedef struct _LotatoMeshNode {
    LotatoMeshNode_pub_key_t pub_key;
    LotatoMeshNode_name_t name;
    uint32_t type;
    uint32_t last_advert;
    int32_t gps_lat;
    int32_t gps_lon;
    uint32_t magic;
} LotatoMeshNode;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LotatoMeshNode_init_default              {{0, {0}}, {0, {0}}, 0, 0, 0, 0, 0}
#define LotatoMeshNode_init_zero                 {{0, {0}}, {0, {0}}, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LotatoMeshNode_pub_key_tag               1
#define LotatoMeshNode_name_tag                  2
#define LotatoMeshNode_type_tag                  3
#define LotatoMeshNode_last_advert_tag           4
#define LotatoMeshNode_gps_lat_tag               5
#define LotatoMeshNode_gps_lon_tag               6
#define LotatoMeshNode_magic_tag                 7

/* Struct field encoding specification for nanopb */
#define LotatoMeshNode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    pub_key,           1) \
X(a, STATIC,   SINGULAR, BYTES,    name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   type,              3) \
X(a, STATIC,   SINGULAR, UINT32,   last_advert,       4) \
X(a, STATIC,   SINGULAR, INT32,    gps_lat,           5) \
X(a, STATIC,   SINGULAR, INT32,    gps_lon,           6) \
X(a, STATIC,   SINGULAR, UINT32,   magic,             7)
#define LotatoMeshNode_CALLBACK NULL
#define LotatoMeshNode_DEFAULT NULL

extern const pb_msgdesc_t LotatoMeshNode_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LotatoMeshNode_fields &LotatoMeshNode_msg

/* Maximum encoded size of messages (where known) */
#define LOTATO_MESH_NODE_PB_H_MAX_SIZE           LotatoMeshNode_size
#define LotatoMeshNode_size                      108

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
